columns:
  order_id: object
  customer_id: object
  order_status: object
  order_purchase_timestamp: object
  order_approved_at: object
  order_delivered_carrier_date: object
  order_delivered_customer_date: object
  order_estimated_delivery_date: object
  payment_sequential: float64
  payment_type: object
  payment_installments: float64
  payment_value: float64
  review_id: object
  review_score: float64
  review_comment_title: object
  review_comment_message: object
  review_creation_date: object
  review_answer_timestamp: object
  order_item_id: int64
  product_id: object
  seller_id: object
  shipping_limit_date: object
  price: float64
  freight_value: float64
  customer_unique_id: object
  customer_zip_code_prefix: int64
  customer_city: object
  customer_state: object

numerical_columns:
  - payment_sequential
  - payment_installments
  - payment_value
  - review_score
  - price
  - freight_value

categorical_columns:
  - order_status
  - payment_type
  - customer_city
  - customer_state
  - customer_zip_code_prefix

drop_columns:
  - customer_id
  - review_id
  - product_id
  - seller_id
  - order_item_id
  - review_comment_title
  - review_comment_message
  - order_approved_at
  - order_delivered_carrier_date
  - review_creation_date
  - review_answer_timestamp
  - shipping_limit_date
  - order_status
  - customer_zip_code_prefix
  - customer_city
  - customer_state
  - payment_sequential
  - payment_type


  # transformed columns 
transformed_columns:
  - Recency
  - Frequency
  - Total_Price
  - Total_Freight
  - Is_churn
  - Freight_ratio
  - Frequency

transfromed_drop_columns:
  - Recency
  - Total_Price
  - Total_Freight
  - customer_unique_id


transformed_numeric_columns:
  - Monetary
  - Average_review_score 
  - total_installments
  - Freight_ratio

target_column: Is_churn

std_scaler_columns:
  - Monetary
  - Average_review_score 
  - total_installments
  - Freight_ratio
  
minmax_scaler_columns:
  - Frequency
